version: "3.8"

services:
    app:
        image: fastapi_demo
        build: .
        volumes:
          - ./:/src
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always
        command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
        depends_on:
            - db
        networks:
            - backend

    db:
        container_name: app_db
        hostname: app_db
        image: mysql:8.0.37
        restart: unless-stopped
        environment:
            MYSQL_USER_: root
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: fastapi
        ports:
            - "3307:3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend

volumes:
  db:

networks:
  backend: