"""Add hashed password field to user

Revision ID: 06250d6525c2
Revises: f9ebd5714034
Create Date: 2024-06-05 10:32:35.871381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06250d6525c2'
down_revision: Union[str, None] = 'f9ebd5714034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('users', sa.Column('salt', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'salt')
    op.create_table('casbin_rule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v0', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v5', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
