"""Add token table

Revision ID: 521225422fa9
Revises: e02bf1743b62
Create Date: 2024-06-05 11:14:51.537093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '521225422fa9'
down_revision: Union[str, None] = 'e02bf1743b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v0', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v5', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
