"""Change datatype of role user

Revision ID: c0e91f01a922
Revises: 9e74122e6e49
Create Date: 2024-06-07 15:21:46.286789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0e91f01a922'
down_revision: Union[str, None] = '9e74122e6e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.INTEGER(),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.String(length=255),
                    type_=mysql.INTEGER(),
                    existing_nullable=True)
    op.create_table('casbin_rule',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('ptype', mysql.VARCHAR(
                        length=255), nullable=True),
                    sa.Column('v0', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('v1', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('v2', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('v3', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('v4', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('v5', mysql.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
