"""Delete salt field in user table

Revision ID: e02bf1743b62
Revises: 06250d6525c2
Create Date: 2024-06-05 10:34:53.599751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e02bf1743b62'
down_revision: Union[str, None] = '06250d6525c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', mysql.VARCHAR(length=20), nullable=True))
    op.create_table('casbin_rule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ptype', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v0', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v3', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v4', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('v5', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
